/**
 * @module orchestrator/audit-writer
 *
 * Parses agent stdout and writes a structured markdown audit log to the ticket directory.
 * parseAgentOutput() is a pure function with no I/O.
 * writeAudit() handles the disk write.
 *
 * Inputs (parseAgentOutput): raw stdout string from the claude agent process.
 * Inputs (writeAudit): ticketDir, role, ticket, AgentRunResult, ParsedAuditData, startedAt.
 * Outputs: be_audit.md or fe_audit.md written to ticketDir.
 * Errors: standard fs errors if write fails.
 */

import { writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Ticket } from '../schemas/index.js';
import type { AgentRunResult } from './agent-runner.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface ParsedAuditData {
  filesRead: string[];
  filesWritten: string[];
  bashCommands: string[];
  summary: string;
  rawOutput: string;
}

// ─── Parser (pure) ────────────────────────────────────────────────────────────

const READ_PATTERNS = [
  /^Reading (\S+)/,
  /^Read file:\s*(\S+)/,
  /^Read:\s*(\S+)/,
];

const WRITE_PATTERNS = [
  /^Creating:\s*(\S+)/,
  /^Updating:\s*(\S+)/,
  /^Write file:\s*(\S+)/,
  /^Edit file:\s*(\S+)/,
  /^Created\s+(\S+)/,
  /^Updated\s+(\S+)/,
  /^Creating migration:\s*(\S+)/,
];

const BASH_PATTERNS = [
  /^Bash:\s*(.+)/,
  /^Running:\s*(.+)/,
  /^\$ (.+)/,
];

export function parseAgentOutput(stdout: string): ParsedAuditData {
  const lines = stdout.split('\n');
  const filesRead = new Set<string>();
  const filesWritten = new Set<string>();
  const bashCommands = new Set<string>();

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed) continue;

    for (const pattern of READ_PATTERNS) {
      const m = pattern.exec(trimmed);
      if (m?.[1]) {
        filesRead.add(m[1]);
        break;
      }
    }

    for (const pattern of WRITE_PATTERNS) {
      const m = pattern.exec(trimmed);
      if (m?.[1]) {
        filesWritten.add(m[1]);
        break;
      }
    }

    for (const pattern of BASH_PATTERNS) {
      const m = pattern.exec(trimmed);
      if (m?.[1]) {
        bashCommands.add(m[1].trim());
        break;
      }
    }
  }

  // Extract summary: last non-empty paragraph (50+ chars), or last non-empty line
  const paragraphs = stdout.split(/\n\s*\n/).map((p) => p.trim()).filter(Boolean);
  let summary = '';
  for (let i = paragraphs.length - 1; i >= 0; i--) {
    const p = paragraphs[i];
    if (p && p.length >= 50) {
      summary = p;
      break;
    }
  }
  if (!summary) {
    const lastLine = lines.filter((l) => l.trim()).pop() ?? '';
    summary = lastLine.trim();
  }

  return {
    filesRead: [...filesRead].sort(),
    filesWritten: [...filesWritten].sort(),
    bashCommands: [...bashCommands].sort(),
    summary,
    rawOutput: stdout,
  };
}

// ─── Writer ───────────────────────────────────────────────────────────────────

function formatListOrNone(items: string[]): string {
  if (items.length === 0) return 'None recorded.';
  return items.map((item) => `- \`${item}\``).join('\n');
}

export async function writeAudit(
  ticketDir: string,
  role: 'be' | 'fe',
  ticket: Ticket,
  result: AgentRunResult,
  parsed: ParsedAuditData,
  startedAt: string,
): Promise<void> {
  const roleLabel = role === 'be' ? 'Backend' : 'Frontend';
  const filename = role === 'be' ? 'be_audit.md' : 'fe_audit.md';
  const auditPath = join(ticketDir, filename);
  const completedAt = new Date().toISOString();
  const durationSeconds = Math.round(result.durationMs / 1000);

  const content = `# ${roleLabel} audit — ${ticket.id}

**Ticket**: ${ticket.title}
**Started**: ${startedAt}
**Completed**: ${completedAt}
**Duration**: ${durationSeconds}s
**Exit code**: ${result.exitCode}
**Branch**: ${result.role === role ? '' : ''}
**Commit**:

## Files read

${formatListOrNone(parsed.filesRead)}

## Files written

${formatListOrNone(parsed.filesWritten)}

## Bash commands executed

${formatListOrNone(parsed.bashCommands)}

## Agent summary

${parsed.summary || 'No summary recorded.'}

---
*Generated by ai-tandem audit-writer. Raw output length: ${parsed.rawOutput.length} chars.*
`;

  await writeFile(auditPath, content, 'utf8');
}
